#!/bin/sh

# Source BSD run command configuration and helper functions
. /etc/rc.conf
. /etc/rc.subr

# Mount /proc and /sys if not already mounted, needed below
mount -a

# Fake writable /etc, /home and /root using overlayfs on /rw, which might be a tmpfs.
if enabled rwoverlay && test -d /rw; then
    mounted /rw || mountmfs /rw $rwsize $rwmfs_flags

    for dir in etc var home root; do
	mkdir -p /rw/.$dir /rw/$dir
	mount -t overlay none /$dir -olowerdir=/$dir,upperdir=/rw/$dir,workdir=/rw/.$dir
    done
else
    enabled varmfs && mountmfs /var $varsize $varmfs_flags
    if enabled populate_var; then
	for dir in cache db empty games lib/alarm lib/misc log mail spool/cron tmp; do
	    mkdir -p /var/$dir
	done
    fi
fi

# Some use-cases might need this, containers usually don't
enabled tmpmfs && mountmfs /tmp $tmpsize $tmpmfs_flags
enabled runmfs && mountmfs /run $runsize $runmfs_flags

# Compat symlink
[ -e /var/run ] || ln -s /run /var/run

# Bring up all /etc/network/interfaces
ifup -a 2>&1 >/dev/null

# Run local start scripts, may be available now after mount -a
[ -x /etc/rc.local ] && /etc/rc.local
