#!/bin/sh
# set -x

# Source BSD run command configuration and helper functions
. /etc/rc.conf
. /etc/rc.subr

# Mount /proc and /sys if not already mounted, needed below
mount -a

# Assuming /dev is Linux devtmpfs
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# For applications using POSIX shm_open() etc.
if enabled shmfs; then
    mkdir -p /dev/shm
    mountmfs /dev/shm $shmsize $shmfs_flags
fi

# Set up device nodes, scan /sys to populate /dev
mdev -s

# Set kernel variables from /etc/sysctl.conf
sysctl -qp 2>/dev/null

# Fake writable /etc, /home and /root using overlayfs on /rw, which might be a tmpfs.
if enabled rwoverlay && test -d /rw; then
    mounted /rw || mountmfs /rw $rwsize $rwmfs_flags

    for dir in etc var home root; do
	mkdir -p /rw/.$dir /rw/$dir
	mount -t overlay none /$dir -olowerdir=/$dir,upperdir=/rw/$dir,workdir=/rw/.$dir
    done

    # Create /etc/mtab compat symlink
    ln -s /proc/mounts /etc/mtab
else
    enabled varmfs && mountmfs /var $varsize $varmfs_flags
    if enabled populate_var; then
	for dir in cache db empty games lib/alarm lib/misc log mail spool/cron tmp; do
	    mkdir -p /var/$dir
	done
    fi
fi

# Some use-cases might need this, containers usually don't
enabled tmpmfs && mountmfs /tmp $tmpsize $tmpmfs_flags
enabled runmfs && mountmfs /run $runsize $runmfs_flags

# Compat symlink
[ -e /var/run ] || ln -s /run /var/run

# Set hostname and bring up all auto /etc/network/interfaces
hostname -F /etc/hostname
ifup -a 2>&1 >/dev/null

# Run local start scripts, may be available now after mount -a
[ -x /etc/rc.local ] && /etc/rc.local
