#!/bin/sh

# Fake writable /etc, /home and /root using a tmpfs, for /etc/fstab
# TODO: Check if host already assigned writable space to /rw
mount -t tmpfs -o size=20% tmpfs /rw
mkdir -p /rw/.etc /rw/etc /rw/.var /rw/var /rw/.home /rw/home /rw/.root /rw/root

# Mount file systems listed in /etc/fstab, notice overlays
mount -a

# Compat symlink
ln -s /run /var/run

# Bring up all /etc/network/interfaces
ifup -a 2>&1 >/dev/null
