#!/bin/sh

# Mount file systems listed in /etc/fstab
mount -a

# create some dirs to avoid warning messages
mkdir -p /var/cache /var/db /var/empty /var/games /var/lib/alarm \
      /var/lib/misc /var/log /var/mail /var/spool/cron /var/tmp

# Compat symlink
ln -s /run /var/run

# Bring up all /etc/network/interfaces
ifup -a 2>&1 >/dev/null
